export const slugs = ['yoga-pilates','boxe','entrainement-prive','course-a-pied','developpement-personnel','bootcamp','strong-nation','stretching'];
export const activityCopy = {
 fr: [
  ['Yoga & Pilates','Activité sereine','Yoga et Pilates guidés dans le studio ONYX. Pilates spécial récupération.','Équilibre intérieur & flexibilité · Respiration consciente · Union du corps et de l’esprit · Réduction du stress & paix','Une pratique guidée, ajustée à votre niveau, dans une atmosphère calme. Le yoga aérien suspendu signe l’expérience ONYX.','Pour retrouver de la mobilité, ralentir et vous reconnecter à votre corps.'],
  ['Sports de combat','Activité Boxe','Boxe Technic, Boxe Fitness, Muay Thaï et Sparring.','Maîtrise de soi & force · Agilité & endurance décuplées · Précision de l’action · Résilience & équilibre','Travail technique, intensité adaptée et progression encadrée par un coach.','Pour découvrir la boxe ou faire évoluer une pratique déjà installée.'],
  ['Entraînement privé','Coaching sur mesure','Personal Training, séance sur mesure, Duo Training et coaching sportif.','Programme personnalisé · Attention dédiée · Progression mesurable · Motivation durable','Un échange sur vos objectifs, suivi d’un entraînement adapté à votre énergie du jour.','Pour avancer avec un cadre clair et un accompagnement individuel.'],
  ['Course à pied','Running Club','Entraînement running et endurance en intérieur, au club ONYX.','Endurance progressive · Cardio · Énergie collective · Rythme adapté','Une séance collective en intérieur pour travailler votre endurance à votre rythme.','Pour celles et ceux qui souhaitent progresser dans un cadre encadré.'],
  ['Développement personnel','Réservez votre équilibre','Ateliers de développement personnel et séance individuelle de préparation mentale 1h.','Libérez-vous de vos blocages · Performance maximisée · Clarté d’esprit · Confiance décuplée','Un temps guidé pour poser vos intentions, explorer vos ressources et construire des repères utiles.','Pour celles et ceux qui souhaitent prendre du recul et avancer avec confiance.'],
  ['Bootcamp','Ensemble, plus fort','Séances de bootcamp intensif.','Force fonctionnelle · Cardio stimulant · Esprit d’équipe · Énergie renouvelée','Des séquences variées, ludiques et progressives au rythme du groupe.','Pour retrouver le plaisir du défi collectif.'],
  ['Strong Nation / Circle Mobility','Rythme & mobilité','Une session portée par la musique, suivie d’un travail ciblé sur la mobilité.','Mouvement rythmé · Coordination · Mobilité articulaire · Énergie collective','Une alternance de séquences dynamiques et de mouvements contrôlés.','Pour celles et ceux qui aiment bouger en musique et délier leur corps.'],
  ['Stretching','Récupération en douceur','Une séance de récupération et de flexibilité dans le studio ONYX.','Souplesse · Récupération active · Respiration · Relâchement','Des étirements guidés pour clôturer la journée et rendre au corps son espace.','Pour faire une pause, récupérer et retrouver de l’amplitude.']
 ],
 en: [
  ['Yoga & Pilates','A mindful practice','Guided yoga and Pilates in the ONYX studio. Pilates focused on recovery.','Inner balance & flexibility · Conscious breathing · Body-mind connection · Stress relief & calm','A guided practice tailored to your level in a calm setting. Suspended aerial yoga is an ONYX signature.','For mobility, a slower pace and a deeper connection with your body.'],
  ['Combat sports','Boxing sessions','Technical boxing, Boxing Fitness, Muay Thai and sparring.','Self-mastery & strength · Greater agility & endurance · Precision · Resilience & balance','Technical work, adapted intensity and steady progress with a coach.','For beginners and experienced boxers alike.'],
  ['Private training','Personal coaching','Personal Training, tailor-made sessions, Duo Training and sports coaching.','Personal plan · Dedicated attention · Measurable progress · Lasting motivation','A conversation about your goals, followed by training shaped around your energy that day.','For focused progress with individual support.'],
  ['Running','Running Club','Indoor running and endurance training at ONYX Club.','Steady endurance · Cardio · Shared energy · Your own pace','A group indoor session to build endurance at your own pace.','For anyone looking to progress with expert guidance.'],
  ['Personal development','Find your balance','Personal development workshops and one-to-one 1h mental preparation sessions.','Release what holds you back · Maximise performance · Clarity of mind · Greater confidence','Guided time to set intentions, explore your resources and build useful habits.','For anyone ready to pause, reflect and move forward with confidence.'],
  ['Bootcamp','Stronger together','Intensive bootcamp sessions.','Functional strength · Uplifting cardio · Team spirit · Renewed energy','Varied, playful and progressive sequences powered by the group.','For anyone who enjoys a shared challenge.'],
  ['Strong Nation / Circle Mobility','Rhythm & mobility','A music-led session followed by focused mobility work.','Rhythmic movement · Coordination · Joint mobility · Shared energy','An alternation of dynamic sequences and controlled movement.','For anyone who likes to move to music and loosen up.'],
  ['Stretching','Gentle recovery','A recovery and flexibility session in the ONYX studio.','Flexibility · Active recovery · Breathing · Release','Guided stretches to close the day and give your body room to move.','For a pause, recovery and greater range of motion.']
 ]
};
