import Image from 'next/image';
import { notFound } from 'next/navigation';
import { activityCopy, slugs } from '@/content/activities';
import { getLang } from '@/lib/i18n';
import Header from '@/components/Header';
import Effects from '@/components/Effects';
import cfg from '@/site.config';
import VisitForm from '@/components/VisitForm';
import { bookingCopy } from '@/content/booking';
export function generateStaticParams(){return ['fr','en'].flatMap(lang=>slugs.map(slug=>({lang,slug})));}
export const dynamicParams=false;
export function generateMetadata({params}:{params:{lang:string;slug:string}}){const index=slugs.indexOf(params.slug);if(index<0)return {};return {title:`${activityCopy[params.lang==='en'?'en':'fr'][index][0]} | Onyx Club`,description:activityCopy[params.lang==='en'?'en':'fr'][index][2]};}
export default function ActivityPage({params}:{params:{lang:string;slug:string}}){const index=slugs.indexOf(params.slug);if(index<0)notFound();const lang=getLang(params.lang);const c=activityCopy[lang][index];const nav=lang==='fr'?['LE CONCEPT','ACTIVITÉS','ÉVÉNEMENT','ÉQUIPE','AVIS','MILKSHAKES','CLIENTÈLE','RÉSERVER']:['CONCEPT','ACTIVITIES','EVENT','TEAM','REVIEWS','SHAKES','COMMUNITY','BOOK'];return <><Effects/><Header lang={lang} nav={nav} cta={lang==='fr'?'DEVENIR MEMBRE':'BECOME A MEMBER'}/><main><section className={`activity-hero activity-${params.slug}`}><p className="lab">{lang==='fr'?'ONYX · ACTIVITÉS':'ONYX · ACTIVITIES'}</p><h1>{c[0]}</h1><p className="lead">{c[2]}</p><a className="btn" href="#booking">{lang==='fr'?'RÉSERVER UNE SÉANCE':'BOOK A SESSION'}</a></section><section className="sec activity-detail"><div><p className="lab">{c[1]}</p><h2>{lang==='fr'?'Une pratique, votre équilibre.':'A practice, your balance.'}</h2><p className="mut">{c[4]}</p><h3>{lang==='fr'?'Pour qui ?':'Who is it for?'}</h3><p className="mut">{c[5]}</p></div><article className="card"><p className="lab">{lang==='fr'?'LES BÉNÉFICES':'THE BENEFITS'}</p>{c[3].split(' · ').map((x:string)=><p className="benefit" key={x}>{x}</p>)}</article></section><section className="sec alt rate-strip"><div><p className="lab">{lang==='fr'?'TARIFS':'PRICING'}</p><h2>{lang==='fr'?'Votre prochaine séance.':'Your next session.'}</h2></div><p><b className="foil">{cfg.prices.group}.00 {cfg.currency}</b><span>{lang==='fr'?'Cours collectif':'Group class'}</span></p><p><b className="foil">{cfg.prices.single}.00 {cfg.currency}</b><span>{lang==='fr'?'Cours individuel':'Private session'}</span></p><a className="btn" href="#booking">{lang==='fr'?'RÉSERVER UNE SÉANCE':'BOOK A SESSION'}</a></section><section className="sec activity-booking" id="booking"><p className="lab">{lang==='fr'?'RÉSERVATION PERSONNALISÉE':'PERSONALISED BOOKING'}</p><h2>{lang==='fr'?`Réserver · ${c[0]}`:`Book · ${c[0]}`}</h2><p className="mut booking-intro">{bookingCopy[lang].note}</p><VisitForm key={slugs[index]} t={bookingCopy[lang]} defaultActivity={slugs[index]} endpoint={cfg.formEndpoint} to={cfg.email}/></section></main><footer className="ft"><a className="footer-logo-link" href={`/${lang}/`} aria-label="Onyx Club home"><Image className="footer-logo-image" src="/images/brand-onyx.png" alt="Onyx Club" width={1000} height={1000} unoptimized/></a><p>SPORT · LIFESTYLE · ZEN · {cfg.address}</p></footer></>}
