import Image from 'next/image';
import { homeLeadCopy } from '@/content/booking';
import { getDict, getLang } from '@/lib/i18n';
import cfg from '@/site.config';
import R from '@/components/Reveal';
import Header from '@/components/Header';
import Preloader from '@/components/Preloader';
import VisitForm from '@/components/VisitForm';
import Effects from '@/components/Effects';
import Cursor from '@/components/Cursor';
import PassTicket from '@/components/PassTicket';
import LocalBusiness from '@/components/LocalBusiness';

const slugs=['yoga-pilates','boxe','entrainement-prive','course-a-pied','developpement-personnel','bootcamp'];
export const dynamicParams=false;
export function generateStaticParams(){return [{lang:'fr'},{lang:'en'}]}
export default function Home({ params }: { params: { lang: string } }) {
  const lang=getLang(params.lang),d=getDict(lang),m=d.marquee.repeat(5);
  return <><Effects/><Cursor/><LocalBusiness/><Preloader/><Header lang={lang} nav={d.nav} cta={d.cta}/><main>
    <section id="top" className="hero"><video className="hero-video" aria-hidden="true" autoPlay muted loop playsInline poster="/images/club/club-training-studio.jpg"><source src="/video/hero-lake.mp4" type="video/mp4"/></video><div className="hero-shade"/><div className="hero-content"><p className="tag">{d.hero.tag}</p><h1 className="foil">{d.hero.title}</h1><a className="btn magnetic" href="#concept">{d.hero.btn}<span>↘</span></a></div><a className="scroll-cue" href="#concept"><span/>{lang==='fr'?'DÉFILER':'SCROLL'}</a><div className="hero-side">{lang==='fr'?'CORPS · ESPRIT · ÉQUILIBRE · COMMUNAUTÉ · RÉSULTATS':'MIND · BODY · BALANCE · COMMUNITY · RESULTS'}</div></section>
    <div className="mq"><span>{m}</span><span>{m}</span></div>
    <section id="concept" className="sec concept"><R><p className="lab">{d.concept.label}</p></R><div className="split"><R className="badge"><span className="foil">{d.concept.badge}</span><small>{lang==='fr'?'SUR LE LAC LÉMAN':'ON LAKE GENEVA'}</small></R><R><h2>{d.concept.title}</h2><p className="mut">{d.concept.sub}</p><p className="concept-manifesto">{lang==='fr'?'Bougez. Respirez. Évoluez.':'Move. Breathe. Evolve.'}</p></R></div><div className="grid g3">{d.concept.items.map((t,i)=><R key={t} className="card icon-card"><span className="icon-mark">{['◌','✳','↗','⌁','✧','◈'][i]}</span>{t}</R>)}</div><div className="stats"><div><span>{lang==='fr'?'CLUB PRIVÉ':'PRIVATE CLUB'}</span></div><div><span>{lang==='fr'?'ACTIVITÉS':'ACTIVITIES'}</span></div><div><span>{lang==='fr'?'POSSIBILITÉS':'POSSIBILITIES'}</span></div></div></section>
    <section id="activites" className="sec alt"><R><p className="lab">{d.acts.label}</p><h2>{d.acts.title}</h2><p className="mut">{d.acts.sub}</p></R><div className="activity-rail">{d.acts.items.map(([t,s],i)=><R key={t} className="card act tilt-card"><span className={`activity-image image-${i+1}`}/><h3>{t}</h3><p className="mut">{s}</p><a className="text-link" href={`/${lang}/activites/${slugs[i]}/`}>{d.detail} <span>↗</span></a></R>)}</div><div className="category-line"><span>YOGA · HIIT · BOXE · BIEN-ÊTRE</span><a className="text-link" href={`/${lang}/tarifs/`}>{lang==='fr'?'VOIR LES TARIFS':'VIEW PRICES'} ↗</a></div><R className="prices"><div><b className="foil">{cfg.prices.group} {cfg.currency}</b><span>{d.acts.group}</span></div><div><b className="foil">{cfg.prices.single} {cfg.currency}</b><span>{d.acts.single}</span></div><a className="btn" href={`/${lang}/contact/`}>{d.acts.btn}</a></R></section>
    <section id="offres" className="sec"><R><p className="lab">{d.offers.label}</p><h2>{d.offers.title}</h2><p className="mut">{d.offers.desc}</p></R><div className="poster-grid">{d.offers.items.map((item,i)=><a className={`poster poster-${i+1}`} href={`/${lang}/galerie/`} key={item}><strong>{item}</strong><small>{lang==='fr'?'VOIR':'VIEW'} ↗</small></a>)}</div></section>
    <section className="feature-boxe"><div className="feature-image"><span>ONYX / BOXE</span></div><div className="feature-copy"><p className="lab">{lang==='fr'?'L’ART DU COMBAT':'THE ART OF BOXING'}</p><h2>{d.boxe.title}</h2><p className="mut">{d.boxe.text}</p><div className="feature-prices"><b className="foil">35 CHF</b><b className="foil">120 CHF</b></div><a className="btn" href={`/${lang}/activites/boxe/`}>{d.acts.btn}</a></div></section>
    <section className="event-teaser"><div><p className="lab">{d.event.label}</p><h2>{d.event.title}</h2><p className="mut">{d.event.desc}</p><a className="text-link" href={`/${lang}/evenement/`}>{d.event.button} ↗</a></div><PassTicket lang={lang} eventDate={cfg.event.date}/></section>
    <section id="avis" className="sec alt"><R><p className="lab">{d.reviews.label}</p><h2>{d.reviews.title}</h2><p className="mut">{lang==='fr'?'Quelques mots de notre communauté.':'A few words from our community.'}</p></R><div className="grid g3">{d.reviews.items.map(([q,a],i)=><R key={a} className="card review-card"><span className="stars">★★★★★</span><p className="q">“{q}”</p><small>{a} · {lang==='fr'?'AVIS DE DÉMONSTRATION':'SAMPLE REVIEW'}</small></R>)}</div></section>
    <section id="milkshakes" className="sec bar-sec"><div className="bar-heading"><R><p className="lab">{d.bar.label}</p><h2 className="foil">{d.bar.title}</h2><p className="mut">{d.bar.sub}</p><a className="text-link" href={`/${lang}/milkshakes/`}>{lang==='fr'?'DÉCOUVRIR LE BAR':'DISCOVER THE BAR'} ↗</a></R></div><div className="shake-grid">{d.bar.shakes.map(([n,ing,k],i)=><R key={n} className="card shake"><Image className="shake-product" src={`/images/club/${['shake-onyx','shake-mocha','shake-matcha','shake-blue-leman'][i]}.jpg`} alt={n} width={900} height={1200} unoptimized/><small>CLEAN LABEL</small><h3>{n}</h3><p className="mut">{ing}</p><b className="foil">{k} {d.bar.kcal}</b></R>)}</div></section>
    <section id="clientele" className="sec clientele"><R><p className="lab">{d.cli.label}</p><h2>{d.cli.title}</h2></R><div className="client-grid">{d.cli.items.map((t,i)=><R key={t} className="client-tile"><span>{t}</span></R>)}</div></section>
    <section id="reserver" className="sec visit-sec"><div><R><p className="lab">{d.visit.label}</p><h2>{d.visit.title}</h2><p className="mut">{d.visit.sub}</p><p className="visit-detail">{cfg.address}<br/><a href="tel:+41786137021">{cfg.phone}</a><br/><a href={`mailto:${cfg.email}`}>{cfg.email}</a></p></R></div><R><VisitForm t={homeLeadCopy[lang]} endpoint={cfg.formEndpoint} to={cfg.email}/></R></section>
  </main><footer className="ft"><a className="footer-logo-link" href={`/${lang}/`} aria-label="Onyx Club home"><Image className="footer-logo-image" src="/images/brand-onyx.png" alt="Onyx Club · Sport · Lifestyle · Zen · Sur le lac Léman" width={1000} height={1000} unoptimized/></a><p>{d.foot.join(' · ')}</p><p className="mut">{cfg.address} · <a href="tel:+41786137021">{cfg.phone}</a> · <a href={`mailto:${cfg.email}`}>{cfg.email}</a></p><div className="footer-links"><a href={`/${lang}/tarifs/`}>{lang==='fr'?'TARIFS':'PRICES'}</a><a href={`/${lang}/equipe/`}>{lang==='fr'?'L’ÉQUIPE':'TEAM'}</a><a href={`/${lang}/faq/`}>FAQ</a><a href={`/${lang}/mentions-legales/`}>{lang==='fr'?'MENTIONS LÉGALES':'LEGAL NOTICE'}</a></div><p className="footer-motto">MIND · BODY · LIFE</p></footer><a className="whatsapp" href="https://wa.me/41786137021" target="_blank" rel="noreferrer" aria-label="WhatsApp">WA</a></>;
}
